### ISSUE TITLE
Add Installation + `setup.py`

### ISSUE THREAD

**Issue by antoninoLorenzo** [RoysManfo/PassLock#14]
The Installation process isn't provided in the `README.md`, so someone that comes across PassLock may not notice the releases.

Also, it would be good being able to install it just by doing `pip install .` (i.e adding `setup.py`); if you want I would enjoy helping you with it.

**Comment by roysmanfo** [comment]
- I didn't think about `pip`, as not everyone has python installed, but now that I think about it it is better to have multiple install options as you suggest.

- I will also modify the README to include the installation process. For now it is as simple as extracting the archive and running the executable inside.

- The code is open source, so fell free to create a pull request with your changes

**Comment by antoninoLorenzo** [comment]
Great, do you want me to work on a branch or directly on the main?

**Comment by roysmanfo** [comment]
You can work on a separate branch on your fork, then you can merge directly in main.
I will then review your changes and confirm the merge.

**Comment by roysmanfo** [comment]
closing issue, as it has been resolved in #15
